### ISSUE TITLE
Modifying to OG Solver

### ISSUE THREAD

**Issue by odgaard** [Mxbonn/strip-packing#1]
Hi, I would really like to use your solver for a personal project, however I can't quite figure out how to modify the solver to not rotate the elements. 

I need to use an OG solver for my SPP. Do you know how to modify the solver to work correctly without rotating the elements? (I tried to disable everything related to rotation in the algorithm, but that produced an incorrect result). 

Thank you for your project! :)

**Comment by Mxbonn** [comment]
Hey @odgaard,
I added a `phsppog` class which implements the OG solver.
Let me know if it behaves as expected ;).

**Comment by odgaard** [comment]
Wow, thank you so much! :D That works great :+1:
